const activityTypes = {
	START_FETCH_ACTIVITIES: 'START_FETCH_ACTIVITIES',
	SUCCESS_FETCH_ACTIVITIES: 'SUCCESS_FETCH_ACTIVITIES',
	FAIL_FETCH_ACTIVITIES: 'FAIL_FETCH_ACTIVITIES',
	
	START_FETCH_ACTIVITIES_BY_TYPES: 'START_FETCH_ACTIVITIES_BY_TYPES',
	SUCCESS_FETCH_ACTIVITIES_BY_TYPES: 'SUCCESS_FETCH_ACTIVITIES_BY_TYPES',
	FAIL_FETCH_ACTIVITIES_BY_TYPES: 'FAIL_FETCH_ACTIVITIES_BY_TYPES',

}

export default activityTypes