const portfolioTypes = {
	START_FETCH_PORTFOLIO: 'START_FETCH_PORTFOLIO',
	SUCCESS_FETCH_PORTFOLIO: 'SUCCESS_FETCH_PORTFOLIO',
	FAIL_FETCH_PORTFOLIO: 'FAIL_REGISTER_PORTFOLIO',
}

export default portfolioTypes