const positionTypes = {
	START_FETCH_ALL_POSITIONS: 'START_FETCH_ALL_POSITIONS',
	SUCCESS_FETCH_ALL_POSITIONS: 'SUCCESS_FETCH_ALL_POSITIONS',
	FAIL_FETCH_ALL_POSITIONS: 'FAIL_FETCH_ALL_POSITIONS',

	START_FETCH_SINGLE_POSITION: 'START_FETCH_SINGLE_POSITION',
	SUCCESS_FETCH_SINGLE_POSITION: 'SUCCESS_FETCH_SINGLE_POSITION',
	FAIL_FETCH_SINGLE_POSITION: 'FAIL_REGISTER_SINGLE_POSITION',

	START_DELETE_SINGLE_POSITION: 'START_DELETE_SINGLE_POSITION',
	SUCCESS_DELETE_SINGLE_POSITION: 'SUCCESS_DELETE_SINGLE_POSITION',
	FAIL_DELETE_SINGLE_POSITION: 'FAIL_DELETE_SINGLE_POSITION',

	START_DELETE_ALL_POSITIONS: 'START_DELETE_ALL_POSITIONS',
	SUCCESS_DELETE_ALL_POSITIONS: 'SUCCESS_DELETE_ALL_POSITIONS',
	FAIL_DELETE_ALL_POSITIONS: 'FAIL_DELETE_ALL_POSITIONS',
}

export default positionTypes