const columnWidth = 150

export const columns = [
	{
		field: "date",
		headerName: "Initiated",
		width: columnWidth,
		type: "date",
	},
	{
		field: 'account',
		headerName: "From Account",
		width: columnWidth*2,
		type: "string",
	},
	{
		field: "country",
		headerName: "Country",
		width: columnWidth,
		type: "string",
	},
	{
		field: "amount",
		headerName: "Amount",
		width: columnWidth,
		type: "string",
	},
	{
		field: "fees",
		headerName: "Fees",
		width: columnWidth,
		type: "string",
	},
	{
		field: "recipient",
		headerName: "Recipient Name",
		width: columnWidth*2,
		type: "string",
	},
	{
		field: "processed",
		headerName: "Processed",
		width: columnWidth*2,
		type: "string",
	},
	{
		field: "state",
		headerName: "State",
		width: columnWidth,
		type: "string",
	},
	{
		field: "option",
		headerName: "Option",
		width: columnWidth,
		type: "string",
	},
];

export const rows = [
	{ 
		id: 1,
		date: "22/10/2022",
		//date: new Date(2022, 10, 21),
		account: "D4D0ufSE325sd",
		country:"Kenya",
		fees:"$ 150.79",
		state:"processing",
		amount:"$ 200",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
	{
		id: 2,
		date: "21/10/2022",
		account: "D4D0ufSE325sd",
		country:"$Uganda",
		fees:"$ 79.55",
		state:"processing",
		amount:"$ 200",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
	{
		id: 3,
		date: "23/10/2022",
		account: "D4D0ufSE325sd",
		country:"Seychelles",
		fees:"$ 550.67",
		state:"processing",
		amount:"$ 200",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
	{
		id: 3,
		date: "20/10/2022",
		account: "D4D0ufSE325sd",
		country:"Tanzania",
		fees:"$ 670.12",
		state:"processing",
		amount:"$ 200 500.00",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
	{
		id: 3,
		date: "21/10/2022",
		account: "D4D0ufSE325sd",
		country:"DRC",
		amount:"$ 201",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
	{
		id: 3,
		date: "20/10/2022",
		account: "D4D0ufSE325sd",
		country:"Angola",
		fees:"$ 512.22",
		state:"processing",
		amount:"$ 200",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
	{
		id: 3,
		date: "24/10/2022",
		account: "D4D0ufSE325sd",
		country:"Botswana",
		fees:"$ 715.57",
		state:"processing",
		amount:"$ 200",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
	{
		id: 3,
		date: "24/10/2022",
		account: "D4D0ufSE325sd",
		country:"Madagascar",
		fees:"$ 2150.09",
		state:"processing",
		amount:"$ 200",
		recipient: "Someone",
		processed: "-",
		option:"-",
	},
];