const orderTypes = {
	START_FETCH_ORDER: "START_FETCH_ORDER",
	SUCCESS_FETCH_ORDER: "SUCCESS_FETCH_ORDER",
	FAIL_FETCH_ORDER: "FAIL_FETCH_ORDER",

	START_POST_ORDER: "START_POST_ORDER",
	SUCCESS_POST_ORDER: "SUCCESS_POST_ORDER",
	FAIL_POST_ORDER: "FAIL_POST_ORDER",

	START_EDIT_ORDER: "START_EDIT_ORDER",
	SUCCESS_EDIT_ORDER: "SUCCESS_EDIT_ORDER",
	FAIL_EDIT_ORDER: "FAIL_EDIT_ORDER",

	START_DELETE_SINGLE_ORDER: "START_DELETE_SINGLE_ORDER",
	SUCCESS_DELETE_SINGLE_ORDER: "SUCCESS_DELETE_SINGLE_ORDER",
	FAIL_DELETE_SINGLE_ORDER: "FAIL_DELETE_SINGLE_ORDER",

	START_DELETE_ALL_ORDER: "START_DELETE_ALL_ORDER",
	SUCCESS_DELETE_ALL_ORDER: "SUCCESS_DELETE_ALL_ORDER",
	FAIL_DELETE_ALL_ORDER: "FAIL_DELETE_ALL_ORDER",
};

export default orderTypes;
