const watchlistTypes = {
	START_FETCH_WATCHLIST: 'START_FETCH_WATCHLIST',
	SUCCESS_FETCH_WATCHLIST: 'SUCCESS_FETCH_WATCHLIST',
	FAIL_FETCH_WATCHLIST: 'FAIL_FETCH_WATCHLIST',

    
	START_POST_WATCHLIST: 'START_POST_WATCHLIST',
	SUCCESS_POST_WATCHLIST: 'SUCCESS_POST_WATCHLIST',
	FAIL_POST_WATCHLIST: 'FAIL_POST_WATCHLIST',

    
	START_DELETE_WATCHLIST: 'START_DELETE_WATCHLIST',
	SUCCESS_DELETE_WATCHLIST: 'SUCCESS_DELETE_WATCHLIST',
	FAIL_DELETE_WATCHLIST: 'FAIL_DELETE_WATCHLIST',
}

export default watchlistTypes