const watchlistTypes = {
	START_FETCH_WATCHLIST: "START_FETCH_WATCHLIST",
	SUCCESS_FETCH_WATCHLIST: "SUCCESS_FETCH_WATCHLIST",
	FAIL_FETCH_WATCHLIST: "FAIL_FETCH_WATCHLIST",

	START_POST_WATCHLIST: "START_POST_WATCHLIST",
	SUCCESS_POST_WATCHLIST: "SUCCESS_POST_WATCHLIST",
	FAIL_POST_WATCHLIST: "FAIL_POST_WATCHLIST",

	START_EDIT_WATCHLIST: "START_EDIT_WATCHLIST",
	SUCCESS_EDIT_WATCHLIST: "SUCCESS_EDIT_WATCHLIST",
	FAIL_EDIT_WATCHLIST: "FAIL_EDIT_WATCHLIST",

	START_ADD_ASSETS_WATCHLIST: "START_ADD_ASSETS_WATCHLIST",
	SUCCESS_ADD_ASSETS_WATCHLIST: "SUCCESS_ADD_ASSETS_WATCHLIST",
	FAIL_ADD_ASSETS_WATCHLIST: "FAIL_ADD_ASSETS_WATCHLIST",

	START_DELETE_WATCHLIST: "START_DELETE_WATCHLIST",
	SUCCESS_DELETE_WATCHLIST: "SUCCESS_DELETE_WATCHLIST",
	FAIL_DELETE_WATCHLIST: "FAIL_DELETE_WATCHLIST",

	START_DELETE_ALL_WATCHLIST: "START_DELETE_ALL_WATCHLIST",
	SUCCESS_DELETE_ALL_WATCHLIST: "SUCCESS_DELETE_ALL_WATCHLIST",
	FAIL_DELETE_ALL_WATCHLIST: "FAIL_DELETE_ALL_WATCHLIST",

	START_DELETE_SYMBOL_WATCHLIST: "START_DELETE_SYMBOL_WATCHLIST",
	SUCCESS_DELETE_SYMBOL_WATCHLIST: "SUCCESS_DELETE_SYMBOL_WATCHLIST",
	FAIL_DELETE_SYMBOL_WATCHLIST: "FAIL_DELETE_SYMBOL_WATCHLIST",
};

export default watchlistTypes;
