export const USAstates = [
    { Name: "N/A"},
	{ Name: "Alabama", abbreviation: "AL" },
	{ Name: "Alaska", abbreviation: "AK" },
	{ Name: "Arizona", abbreviation: "AZ" },
	{ Name: "Arkansas", abbreviation: "AR" },
	{ Name: "California", abbreviation: "CA" },
	{ Name: "Colorado", abbreviation: "CO" },
	{ Name: "Connecticut", abbreviation: "CT" },
	{ Name: "Delaware", abbreviation: "DE" },
	{ Name: "Florida", abbreviation: "FL" },
	{ Name: "Georgia", abbreviation: "GA" },
	{ Name: "Hawaii", abbreviation: "HI" },
	{ Name: "Idaho", abbreviation: "ID" },
	{ Name: "Illinois", abbreviation: "IL" },
	{ Name: "Indiana", abbreviation: "IN" },
	{ Name: "Iowa", abbreviation: "IA" },
	{ Name: "Kansas", abbreviation: "KS" },
	{ Name: "Kentucky", abbreviation: "KY" },
	{ Name: "Louisiana", abbreviation: "LA" },
	{ Name: "Maine", abbreviation: "ME" },
	{ Name: "Maryland", abbreviation: "MD" },
	{ Name: "Massachusetts", abbreviation: "MA" },
	{ Name: "Michigan", abbreviation: "MI" },
	{ Name: "Minnesota", abbreviation: "MN" },
	{ Name: "Mississippi", abbreviation: "MS" },
	{ Name: "Missouri", abbreviation: "MO" },
	{ Name: "Montana", abbreviation: "MT" },
	{ Name: "Nebraska", abbreviation: "NE" },
	{ Name: "Nevada", abbreviation: "NV" },
	{ Name: "New Hampshire", abbreviation: "NH" },
	{ Name: "New Jersey", abbreviation: "NJ" },
	{ Name: "New Mexico", abbreviation: "NM" },
	{ Name: "New York", abbreviation: "NY" },
	{ Name: "North Carolina", abbreviation: "NC" },
	{ Name: "North Dakota", abbreviation: "ND" },
	{ Name: "Ohio", abbreviation: "OH" },
	{ Name: "Oklahoma", abbreviation: "OK" },
	{ Name: "Oregon", abbreviation: "OR" },
	{ Name: "Pennsylvania", abbreviation: "PA" },
	{ Name: "Rhode Island", abbreviation: "RI" },
	{ Name: "South Carolina", abbreviation: "SC" },
	{ Name: "South Dakota", abbreviation: "SD" },
	{ Name: "Tennessee", abbreviation: "TN" },
	{ Name: "Texas", abbreviation: "TX" },
	{ Name: "Utah", abbreviation: "UT" },
	{ Name: "Vermont", abbreviation: "VT" },
	{ Name: "Virginia", abbreviation: "VA" },
	{ Name: "Washington", abbreviation: "WA" },
	{ Name: "West Virginia", abbreviation: "WV" },
	{ Name: "Wisconsin", abbreviation: "WI" },
	{ Name: "Wyoming", abbreviation: "WY" },
];
