export const USAstates = [
    { Name: 'ALABAMA', abbreviation: 'AL'},
    { Name: 'ALASKA', abbreviation: 'AK'},
    { Name: 'AMERICAN SAMOA', abbreviation: 'AS'},
    { Name: 'ARIZONA', abbreviation: 'AZ'},
    { Name: 'ARKANSAS', abbreviation: 'AR'},
    { Name: 'CALIFORNIA', abbreviation: 'CA'},
    { Name: 'COLORADO', abbreviation: 'CO'},
    { Name: 'CONNECTICUT', abbreviation: 'CT'},
    { Name: 'DELAWARE', abbreviation: 'DE'},
    { Name: 'DISTRICT OF COLUMBIA', abbreviation: 'DC'},
    { Name: 'FEDERATED STATES OF MICRONESIA', abbreviation: 'FM'},
    { Name: 'FLORIDA', abbreviation: 'FL'},
    { Name: 'GEORGIA', abbreviation: 'GA'},
    { Name: 'GUAM', abbreviation: 'GU'},
    { Name: 'HAWAII', abbreviation: 'HI'},
    { Name: 'IDAHO', abbreviation: 'ID'},
    { Name: 'ILLINOIS', abbreviation: 'IL'},
    { Name: 'INDIANA', abbreviation: 'IN'},
    { Name: 'IOWA', abbreviation: 'IA'},
    { Name: 'KANSAS', abbreviation: 'KS'},
    { Name: 'KENTUCKY', abbreviation: 'KY'},
    { Name: 'LOUISIANA', abbreviation: 'LA'},
    { Name: 'MAINE', abbreviation: 'ME'},
    { Name: 'MARSHALL ISLANDS', abbreviation: 'MH'},
    { Name: 'MARYLAND', abbreviation: 'MD'},
    { Name: 'MASSACHUSETTS', abbreviation: 'MA'},
    { Name: 'MICHIGAN', abbreviation: 'MI'},
    { Name: 'MINNESOTA', abbreviation: 'MN'},
    { Name: 'MISSISSIPPI', abbreviation: 'MS'},
    { Name: 'MISSOURI', abbreviation: 'MO'},
    { Name: 'MONTANA', abbreviation: 'MT'},
    { Name: 'NEBRASKA', abbreviation: 'NE'},
    { Name: 'NEVADA', abbreviation: 'NV'},
    { Name: 'NEW HAMPSHIRE', abbreviation: 'NH'},
    { Name: 'NEW JERSEY', abbreviation: 'NJ'},
    { Name: 'NEW MEXICO', abbreviation: 'NM'},
    { Name: 'NEW YORK', abbreviation: 'NY'},
    { Name: 'NORTH CAROLINA', abbreviation: 'NC'},
    { Name: 'NORTH DAKOTA', abbreviation: 'ND'},
    { Name: 'NORTHERN MARIANA ISLANDS', abbreviation: 'MP'},
    { Name: 'OHIO', abbreviation: 'OH'},
    { Name: 'OKLAHOMA', abbreviation: 'OK'},
    { Name: 'OREGON', abbreviation: 'OR'},
    { Name: 'PALAU', abbreviation: 'PW'},
    { Name: 'PENNSYLVANIA', abbreviation: 'PA'},
    { Name: 'PUERTO RICO', abbreviation: 'PR'},
    { Name: 'RHODE ISLAND', abbreviation: 'RI'},
    { Name: 'SOUTH CAROLINA', abbreviation: 'SC'},
    { Name: 'SOUTH DAKOTA', abbreviation: 'SD'},
    { Name: 'TENNESSEE', abbreviation: 'TN'},
    { Name: 'TEXAS', abbreviation: 'TX'},
    { Name: 'UTAH', abbreviation: 'UT'},
    { Name: 'VERMONT', abbreviation: 'VT'},
    { Name: 'VIRGIN ISLANDS', abbreviation: 'VI'},
    { Name: 'VIRGINIA', abbreviation: 'VA'},
    { Name: 'WASHINGTON', abbreviation: 'WA'},
    { Name: 'WEST VIRGINIA', abbreviation: 'WV'},
    { Name: 'WISCONSIN', abbreviation: 'WI'},
    { Name: 'WYOMING', abbreviation: 'WY' }
]