const userTypes = {
	START_FETCH_USER: 'START_FETCH_USER',
	SUCCESS_FETCH_USER: 'SUCCESS_FETCH_USER',
	FAIL_FETCH_USER: 'FAIL_REGISTER_USER',

	START_FETCH_ME: 'START_FETCH_ME',
	SUCCESS_FETCH_ME: 'SUCCESS_FETCH_ME',
	FAIL_FETCH_ME: 'FAIL_FETCH_ME',

	START_FETCH_ALL_USERS: 'START_FETCH_ALL_USERS',
	SUCCESS_FETCH_ALL_USERS: 'SUCCESS_FETCH_ALL_USERS',
	FAIL_FETCH_ALL_USERS: 'FAIL_FETCH_ALL_USERS',

	START_SETUP_USER: 'START_SETUP_USER',
	SUCCESS_SETUP_USER: 'SUCCESS_SETUP_USER',
	FAIL_SETUP_USER: 'FAIL_SETUP_USER',
}

export default userTypes